### ISSUE TITLE
Numbers on every tab, not only first ones

### ISSUE THREAD

**Issue by leet0rz** [tuomassalo/tab-numbering#3]
Title, pls make it so that there are numbers on all of them :)

**Comment by micgro42** [comment]
I would like to second this request. This feature would be useful when used with extensions like [tridactyl](https://addons.mozilla.org/en-US/firefox/addon/tridactyl-vim/) that allow switch to an arbitrary tab by number.

**Comment by glacambre** [comment]
@micgro42 If you use Tridactyl and its native messenger, you can use `:guiset tabs count` and then `:restart` in order to have numbers inserted into them like this:
![screenshot_2018-11-06-02 31 20](https://user-images.githubusercontent.com/11534587/48037346-1895fb00-e16c-11e8-92ae-a9da38b8869d.png)

If you don't want to run the native messenger, know that we do this just by inserting the following lines in your userChrome.css and thus you can do it manually :)
```css
tabs {
  counter-reset: tab-counter;
}

.tab-label::before {
  counter-increment: tab-counter;
  content: counter(tab-counter) " - ";
}
```
